# -*- coding: utf-8 -*-
"""python project 8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V9D-pqTuDgWKJh_oMQZcSXbbeulMs_XO

Sales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14v8_yoD5ZYTOA4CSV9hxEIbY3yK9eZ8W
"
"""

!pip install faker
import pandas as pd
import numpy as np
import random
from faker import Faker
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

fake = Faker()

stores = ['Store_A', 'Store_B', 'Store_C', 'Store_D']
items = ['Laptop', 'Mobile', 'Tablet', 'Headphones', 'Camera']
regions = ['North', 'South', 'East', 'West']

data = []

for i in range(1000):
    date = fake.date_between(start_date='-2y', end_date='today')
    store = random.choice(stores)
    item = random.choice(items)
    region = random.choice(regions)

    sales = random.randint(10, 500)

    data.append([date, store, item, region, sales])

df = pd.DataFrame(data, columns=[
    'Date', 'Store', 'Item', 'Region', 'Sales'
])

df.head()

df['Date'] = pd.to_datetime(df['Date'])
df = df.sort_values(by='Date')

print(df.isnull().sum())

df = df.drop_duplicates()

df.info()

print("Total Sales:", df['Sales'].sum())
print("Average Sales:", df['Sales'].mean())
print("Max Sales:", df['Sales'].max())
print("Min Sales:", df['Sales'].min())

trend = df.groupby('Date')['Sales'].sum()

plt.figure(figsize=(12, 6))
trend.plot(color='steelblue')
plt.title("Sales Trend Over Time")
plt.xlabel("Date")
plt.ylabel("Sales")
plt.grid(True)
plt.show()

df['Month'] = df['Date'].dt.to_period('M').astype(str)
monthly = df.groupby('Month')['Sales'].sum().reset_index()

fig = px.bar(monthly, x='Month', y='Sales', title="Monthly Sales",
             color='Month',
             labels={'Month': 'Month', 'Sales': 'Total Sales'})
fig.update_layout(showlegend=True)
fig.show()

item_sales = df.groupby('Item')['Sales'].sum().reset_index() # Reset index to get Item as a column

fig = px.bar(item_sales, x='Item', y='Sales', title="Sales by Product",
             color='Item',
             labels={'Item': 'Product', 'Sales': 'Total Sales'})
fig.update_layout(showlegend=True)
fig.show()

region_sales = df.groupby('Region')['Sales'].sum().reset_index()

fig = px.pie(region_sales, values='Sales', names='Region', title="Sales by Region",
             color_discrete_sequence=px.colors.sequential.RdBu)
fig.update_traces(textposition='inside', textinfo='percent+label')
fig.update_layout(showlegend=True)
fig.show()

plt.figure(figsize=(10, 6))
sns.histplot(data=df, x='Sales', hue='Region', bins=30, kde=True)
plt.title("Sales Distribution by Region")
plt.xlabel("Sales")
plt.ylabel("Frequency")
plt.legend(title='Region')
plt.show()

plt.figure(figsize=(10, 6))
sns.boxplot(data=df, x='Region', y='Sales', hue='Region', palette='viridis', legend=False) # Use 'Region' on x-axis and hue for differentiation
plt.title("Sales Distribution and Outliers by Region")
plt.xlabel("Region")
plt.ylabel("Sales")
plt.show()

import numpy as np


numerical_cols = df.select_dtypes(include=[np.number]).columns.tolist()


categorical_cols = ['Store', 'Item', 'Region']


df_encoded_cat = pd.get_dummies(df[categorical_cols], drop_first=True)


df_for_corr = pd.concat([df[numerical_cols], df_encoded_cat], axis=1)

corr = df_for_corr.corr()


plt.figure(figsize=(12, 10))
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5, cbar_kws={'label': 'Correlation Coefficient'}) # Use a divergent colormap and label the color bar
plt.title("Correlation Heatmap of Sales and Encoded Features")
plt.show()